### ISSUE TITLE
关于so库大小的问题

### ISSUE THREAD

**Issue by qingjixian** [chenenyu/AndroidSecurity#1]
我想问一下, cmake生成的so库都很大, 我看你的so库只有18k  是通过ndk生成的吗？ 还是cmake?

**Comment by chenenyu** [comment]
cmake. 你的so库很大，可能是没经过压缩。

**Comment by qingjixian** [comment]
@chenenyu  能详细一点吗？ 以为默认配置 确实很大~ 如果压缩的话如何进行压缩呢？

**Comment by chenenyu** [comment]
`build/transforms/strip...`

**Comment by qingjixian** [comment]
@chenenyu  谢谢哈~  希望能把这个压缩也加到你的项目上,  因为这个问题 问的人也挺多的~

**Comment by zmjios** [comment]
请问一下怎么压缩so文件？

**Comment by zmjios** [comment]
> @chenenyu 谢谢哈~ 希望能把这个压缩也加到你的项目上, 因为这个问题 问的人也挺多的~

后面怎么压缩呢，cmakelist生成的so很大，其实我的代码没几行

**Comment by chenenyu** [comment]
@zmjios 你看看打包到apk里的so其实很小的。
